version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
    time: "12:00"
  pull-request-branch-name:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "12:00"
  pull-request-branch-name:
