name: Linting

on:
 - push

jobs:
  run-linting:
    name: Run linting
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform:
         - ubuntu-latest
        node-version:
         - 12.x
         - 14.x

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install all the things
      run: npm ci # clean install
    - name: Lint all the JavaScripts
      run: npm run lint:javascript
    - name: Lint all the tests
      run: npm run lint:tests
