name: Linting

on:
 - push

jobs:
  run-linting:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v2.1.4
      with:
        path: node_modules
        key: 14.x-${{ runner.OS }}-${{ hashFiles('package-lock.json') }}
    - run: npm ci
    - run: npm run lint:javascript
    - run: npm run lint:tests
