name: Linting

on:
 - push

jobs:
  run-linting:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install all the things
      run: npm ci # clean install
    - name: Lint all the JavaScripts
      run: npm run lint:javascript
    - name: Lint all the tests
      run: npm run lint:tests
