name: "Release package"

on:
  release:
    types: [ "created" ]

jobs:
  lint-and-test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-node@v1"
        with:
          node-version: "14.x"
      - run: "npm ci"
      - run: "npm run lint"
      - run: "npm test"

  # publish-to-npm:
  #   needs: "lint-and-test"
  #   runs-on: "ubuntu-latest"
  #   steps:
  #     - uses: "actions/checkout@v2"
  #     - uses: "actions/setup-node@v1"
  #       with:
  #         node-version: "14.x"
  #         registry-url: "https://registry.npmjs.org/"
  #     - run: "npm ci"
  #     - run: "npm publish"
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-to-github:
    needs: "lint-and-test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-node@v1"
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com/"
      - run: "npm ci"
      - run: "npm publish"
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
