name: Run all tests

on:
 - push

jobs:
  run-filter-function-unit-tests:
    name: Run filter function unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x
    - name: Cache all the things
      id: cache-modules
      uses: actions/cache@v2.1.5
      with:
        path: node_modules
        key: 14.x-${{ runner.OS }}-${{ hashFiles('package-lock.json') }}
    - run: npm ci
    - run: npm test
